name: Rust

on:
  push:
    branches: ['release'] # 触发条件：当有 push 到 release 分支时
  # pull_request:
  #   branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build: # 定义一个名为 build 的 job
    runs-on: ${{ matrix.os }} # 指定 runner 平台，使用 matrix 变量（见下）
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # 定义 matrix，分别在 Ubuntu 和 macOS 上各跑一遍

    steps:
      - uses: actions/checkout@v3 # 第一步：拉取你的仓库代码到 runner

      - uses: actions-rs/toolchain@v1 # 第二步：安装 Rust 工具链
        with:
          toolchain: stable # 安装 stable 版本的 Rust
          override: true # 设置为默认工具链

      - name: Build with Cargo # 第三步：用 cargo 编译 release 版本
        run: cargo build --release

      - name: Get version
        id: version
        run: echo "version=$(grep '^version =' Cargo.toml | head -1 | cut -d '"' -f2)" >> $GITHUB_OUTPUT

      - name: Set short platform name
        id: set_platform
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            echo "platform_short=linux" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            echo "platform_short=darwin" >> $GITHUB_OUTPUT
          else
            echo "platform_short=unknown" >> $GITHUB_OUTPUT
          fi

      - name: Upload arv binary
        uses: actions/upload-artifact@v4
        with:
          name: arv-${{ steps.set_platform.outputs.platform_short }}-v${{ steps.version.outputs.version }}
          path: target/release/arv
